AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Creates a HTTP API Function and DynamoDB datatable
Resources:
  LoadCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: loadcounter2
      PrimaryKey:
          Name: appname
          Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
    ManageCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        AmazonDynamoDBFullAccess
      Events:
        CounterAccessApi:
          Type: Api
          Properties:
            Path: /counter
            Method: get

Outputs:
    CounterAccessApi:
      Description: "endpoint for api to python "
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter/"



